name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Python FastAPI
    steps:
      - uses: actions/checkout@v4

      - name: Check Environment Variables
        run: |
          if [ -z "${{ env.MONGO_CONN }}" ]; then
            echo "MONGO_CONN environment variable is not set"
            exit 1
          fi
          if [ -z "${{ env.MONGO_USER }}" ]; then
            echo "MONGO_USER environment variable is not set"
            exit 1
          fi
          if [ -z "${{ env.MONGO_PW }}" ]; then
            echo "MONGO_PW environment variable is not set"
            exit 1
          fi
        env:
          MONGO_CONN: ${{ secrets.MONGO_CONN }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PW: ${{ secrets.MONGO_PW }}

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests and collect coverage
        run: pytest --cov=src tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: quickstark/quickstark-fastapi-images
